apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespaces/overlays/prod
  - ../../postgres/overlays/prod
  - ../../redis/overlays/prod
  - ../../kafka/overlays/prod
  - ../../s3/overlays/prod
  - ../../monitoring/overlays/prod
  - ../../apps/overlays/prod
